# Generated by Django 5.1 on 2024-08-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('quiz_fiel1', models.FileField(upload_to='quiz1/')),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('updated_at1', models.DateTimeField(auto_now=True)),
                ('category1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz1.category1')),
            ],
        ),
    ]
