# Generated by Django 5.1 on 2024-08-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category1',
            options={'verbose_name_plural': 'Catergories'},
        ),
        migrations.AlterModelOptions(
            name='quiz1',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
