# Generated by Django 5.1 on 2024-08-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0002_alter_category1_options_alter_quiz1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category1',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
