# Generated by Django 5.1 on 2024-08-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0003_alter_category1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz1',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz1.category1'),
        ),
    ]
